-- V31: Card type default limit profile — used on approve/generate to stamp LIMIT_PROFILE on the card.
-- Prefer CARD_TYPE.DEFAULT_LIMIT_PROFILE_ID; cms.card.mobile-default-limit-profile (STD) remains last-resort fallback.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD DEFAULT_LIMIT_PROFILE_ID NUMBER(19)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD CONSTRAINT FK_CARD_TYPE_DEFAULT_LIMIT_PROFILE
    FOREIGN KEY (DEFAULT_LIMIT_PROFILE_ID) REFERENCES LIMIT_PROFILE (ID)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-2275, -2264, -942) THEN RAISE; END IF;
END;
/

UPDATE CARD_TYPE ct
SET ct.DEFAULT_LIMIT_PROFILE_ID = (
  SELECT lp.ID FROM LIMIT_PROFILE lp WHERE lp.PROFILE_CODE = 'STD' AND ROWNUM = 1
)
WHERE ct.DEFAULT_LIMIT_PROFILE_ID IS NULL
  AND EXISTS (SELECT 1 FROM LIMIT_PROFILE lp WHERE lp.PROFILE_CODE = 'STD');

-- Seed CARD_LIMIT_PROFILE rows for STD so cms-app can join by PROFILE_ID (= LIMIT_PROFILE.ID as varchar)
BEGIN
  FOR r IN (SELECT ID, ATM_DAILY_AMOUNT, POS_DAILY_AMOUNT, ECOMMERCE_DAILY_AMOUNT
              FROM LIMIT_PROFILE WHERE PROFILE_CODE = 'STD') LOOP
    BEGIN
      INSERT INTO CARD_LIMIT_PROFILE (PROFILE_ID, CHANNEL_CODE, TRAN_CODE, MAX_LIMIT, SINGLE_TRAN_LIMIT, IS_DEFAULT)
      VALUES (TO_CHAR(r.ID), '1', '1', NVL(r.ATM_DAILY_AMOUNT, 0), NVL(r.ATM_DAILY_AMOUNT, 0), 1);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
    END;
    BEGIN
      INSERT INTO CARD_LIMIT_PROFILE (PROFILE_ID, CHANNEL_CODE, TRAN_CODE, MAX_LIMIT, SINGLE_TRAN_LIMIT, IS_DEFAULT)
      VALUES (TO_CHAR(r.ID), '2', '2', NVL(r.POS_DAILY_AMOUNT, 0), NVL(r.POS_DAILY_AMOUNT, 0), 1);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
    END;
    BEGIN
      INSERT INTO CARD_LIMIT_PROFILE (PROFILE_ID, CHANNEL_CODE, TRAN_CODE, MAX_LIMIT, SINGLE_TRAN_LIMIT, IS_DEFAULT)
      VALUES (TO_CHAR(r.ID), '3', '3', NVL(r.ECOMMERCE_DAILY_AMOUNT, 0), NVL(r.ECOMMERCE_DAILY_AMOUNT, 0), 1);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
END;
/

COMMIT;
