-- Minimal H2 schema for Oracle-only CMS menu tables.
-- Flyway migrations are disabled in the `test` profile, and these tables
-- are not created by Hibernate entities, but MenuService uses raw SQL.

CREATE TABLE CMS_MENU (
  ID BIGINT NOT NULL PRIMARY KEY,
  MENU_NAME VARCHAR(100) NOT NULL,
  MENU_PATH VARCHAR(255) NOT NULL,
  PARENT_MENU_ID BIGINT NULL,
  MENU_ICON VARCHAR(50),
  SORT_ORDER INT DEFAULT 0,
  STATUS CHAR(1) DEFAULT 'Y'
);

CREATE INDEX IDX_CMS_MENU_STATUS ON CMS_MENU (STATUS);
CREATE INDEX IDX_CMS_MENU_PARENT ON CMS_MENU (PARENT_MENU_ID);

CREATE TABLE CMS_ROLE_MENU (
  ID BIGINT NOT NULL PRIMARY KEY,
  ROLE_CODE VARCHAR(50) NOT NULL,
  MENU_ID BIGINT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_CMS_ROLE_MENU_ROLE_CODE ON CMS_ROLE_MENU (ROLE_CODE);
CREATE INDEX IDX_CMS_ROLE_MENU_MENU_ID ON CMS_ROLE_MENU (MENU_ID);

